
// This shows The Simplified Implementing Syntax.
// This file is part of the module ExampleShaderModule, and
// the Primary (root) file is located at:
// ../../ExampleShaderModule.slang

implementing "ExampleShaderModule.slang";

namespace FooNameSpace.Interfaces
{
	/* Example interface InterfaceFoo2. */
	interface InterfaceFoo2
	{
		int myMethod(float arg);
        bool myMethod2(float arg);
	}
}